name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ffmpeg, zip
      run: sudo apt-get install -y ffmpeg zip
    - name: Create sound asset pack
      run: node build.mjs --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "OpenRCT2 Sound FX Asset Pack"
        path: out/**/*
